"""
Django settings for QURAN_UL_EMAN project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-djpwy1gy$ff!qwr60b^&gazj=e(kdf0nd5cv1gey#*_!lx=^(*'

# SECURITY WARNING: Turn off Debug mode in production!
DEBUG = False

# Allow only specific hosts
ALLOWED_HOSTS = ['34.228.244.243', 'sughaat.com', 'www.sughaat.com', 'localhost']


# Allow trusted domains for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    "http://sughaat.com",
    "https://sughaat.com",
    "http://www.sughaat.com",
    "https://www.sughaat.com"
]

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_app',
    'bootstrap4',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'QURAN_UL_EMAN.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Use WSGI for Nginx + Gunicorn
WSGI_APPLICATION = 'QURAN_UL_EMAN.wsgi.application'

# ASGI for Channels (if needed)
ASGI_APPLICATION = 'QURAN_UL_EMAN.asgi.application'

# Channel layers configuration for real-time notifications
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Database Configuration (Using SQLite for now)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Collect static files here

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin settings (Admin panel customization)
JAZZMIN_SETTINGS = {
    "site_title": "My Site Admin",
    "site_header": "Admin Dashboard",
    "site_logo": "images/logo.png",
    "welcome_sign": "Welcome to My Admin Panel",
    "search_model": ["auth.User", "myapp.MyModel"],
    "user_avatar": "profile_pics/",
    "topmenu_links": [
        {"name": "Home", "url": "/", "new_window": False},
        {"name": "Docs", "url": "https://docs.djangoproject.com/", "new_window": True},
    ],
    "default_icon": "fa fa-home",
    "nav_sidebar": True,
    "theme": "default",
}
