# Generated by Django 5.1.4 on 2025-01-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_islamiccalendarevent_day_of_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haddess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ur', models.CharField(max_length=100)),
                ('title_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description_ur', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
